### ISSUE TITLE
Cannot Find Module ‘@vyke/dom’ in Vite SSR

### ISSUE THREAD

**Issue by jakubdonovan** [albizures/vyke-dom#1]
I’m encountering an issue when trying to import @vyke/dom in my SvelteKit app.

Here’s the relevant import in +page.server.ts:
```ts
import { query, select, selectIn } from "@vyke/dom";

 const sanitizedHtml = html.replace(
    /<(style|script)[^>]*>[\s\S]*?<\/\1>/gim,
    "",
  );

const dom = selectIn(sanitizedHtml, query("#owl-demo"));
```
When running the project, I receive the following error:
> [vite] Pre-transform error: Failed to load url @vyke/dom (resolved id: @vyke/dom) in /src/routes/admin/tools/download-images/+page.server.ts. Does the file exist?
> Error: Cannot find module '@vyke/dom' imported from '/src/routes/admin/tools/download-images/+page.server.ts'

![Screenshot 2024-10-15 at 03 08 31](https://github.com/user-attachments/assets/8a06a344-a637-4f9b-808f-f574199b5c85)

**Comment by albizures** [comment]
It seems you're using the `selectIn` function from the server, most (if not all) of the functions within `vyke/dom` are client only

**Comment by jakubdonovan** [comment]
> It seems you're using the `selectIn` function from the server, most (if not all) of the functions within `vyke/dom` are client only

Right, yeah I thought I could parse a html string but it looks like this lib serves a different purpose. I ended up going with jsdom instead.

**Comment by albizures** [comment]
Yeah `vyke/dom` is just a different abstraction for some dom APIs, like jquery. I think it should work alongside jsdom though
